"""
Django settings for hangarin project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import ipaddress
import os
import re
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=()):
    value = os.getenv(name)
    if value is None:
        return list(default)
    return [item.strip() for item in value.split(",") if item.strip()]


_HOST_LABEL_RE = re.compile(
    r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?", re.IGNORECASE
)


def _is_hostname_pattern(value):
    """Accept a hostname or Django's leading-dot subdomain pattern, never a URL."""
    hostname = value[1:] if value.startswith(".") else value
    if not hostname or not hostname.isascii() or len(hostname) > 253:
        return False
    if hostname.startswith("[") and hostname.endswith("]"):
        try:
            return isinstance(ipaddress.ip_address(hostname[1:-1]), ipaddress.IPv6Address)
        except ValueError:
            return False
    return all(_HOST_LABEL_RE.fullmatch(label) for label in hostname.split("."))


def _https_origin_hostname(value):
    """Return the hostname for a path-free HTTPS origin, or None if it is unsafe."""
    try:
        origin = urlsplit(value)
        _ = origin.port  # Accessing port also validates its syntax and range.
    except ValueError:
        return None
    if (
        origin.scheme.lower() != "https"
        or not origin.hostname
        or origin.hostname.startswith(".")
        or origin.username is not None
        or origin.password is not None
        or origin.path
        or origin.query
        or origin.fragment
        or not _is_hostname_pattern(origin.hostname)
    ):
        return None
    return origin.hostname.lower()


def _allowed_host_covers(hostname, allowed_host):
    """Match exact hosts plus Django's `.example.com` apex/subdomain syntax."""
    normalized = allowed_host.lower()
    if normalized.startswith("."):
        return hostname == normalized[1:] or hostname.endswith(normalized)
    if normalized.startswith("[") and normalized.endswith("]"):
        normalized = normalized[1:-1]
    return hostname == normalized


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

ENVIRONMENT = os.getenv("DJANGO_ENV", "development").strip().lower()
IS_PRODUCTION = ENVIRONMENT == "production"
ALLOW_PRODUCTION_SEED = env_bool("HANGARIN_ALLOW_PRODUCTION_SEED", default=False)

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
if IS_PRODUCTION and (
    not SECRET_KEY or SECRET_KEY.startswith("django-insecure-")
):
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must contain a non-development value in production."
    )
if not SECRET_KEY:
    SECRET_KEY = "django-insecure-hangarin-local-development-only"

DEBUG = env_bool("DJANGO_DEBUG", default=not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DJANGO_DEBUG must be False in production.")

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=("127.0.0.1", "localhost", "testserver") if not IS_PRODUCTION else (),
)
CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=("http://127.0.0.1:8000", "http://localhost:8000")
    if not IS_PRODUCTION
    else (),
)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must list the deployed hostname in production."
    )
if IS_PRODUCTION and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured(
        "DJANGO_CSRF_TRUSTED_ORIGINS must list the deployed HTTPS origin in production."
    )
if IS_PRODUCTION:
    if any(
        host == "*" or not _is_hostname_pattern(host) for host in ALLOWED_HOSTS
    ):
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS must contain hostname-only values in production; "
            "wildcards, schemes, ports, and paths are not allowed."
        )

    for trusted_origin in CSRF_TRUSTED_ORIGINS:
        origin_hostname = _https_origin_hostname(trusted_origin)
        if origin_hostname is None:
            raise ImproperlyConfigured(
                "DJANGO_CSRF_TRUSTED_ORIGINS must contain path-free https:// "
                "origins in production."
            )
        if not any(
            _allowed_host_covers(origin_hostname, allowed_host)
            for allowed_host in ALLOWED_HOSTS
        ):
            raise ImproperlyConfigured(
                "Every DJANGO_CSRF_TRUSTED_ORIGINS hostname must be covered by "
                "DJANGO_ALLOWED_HOSTS in production."
            )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hangarin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hangarin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_HSTS_SECONDS = (
    31536000 if IS_PRODUCTION and env_bool('DJANGO_ENABLE_HSTS') else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': (
            'django.core.mail.backends.smtp.EmailBackend'
            if IS_PRODUCTION
            else 'django.core.mail.backends.console.EmailBackend'
        ),
    },
}
